package spamassasin100;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Data_Model_SPAM100
 * Kelas yang akan mengerjakan prosedur pemilihan lokasi dataset dan 
 * file yang akan menyimpan hasil pemodelan.
 * @author Albertus Kelvin
 */
public class Data_Model_SPAM100 extends javax.swing.JFrame {

    /**
     * Konstruktor
     * inisiasi komponen user interface
     */
    public Data_Model_SPAM100() {
        initComponents();
        jTextField_datasetLOC.setEditable(false);
        jTextField_modelLOC.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_datasetLOC = new javax.swing.JPanel();
        jButton_datasetLOC = new javax.swing.JButton();
        jTextField_datasetLOC = new javax.swing.JTextField();
        jPanel_modelLOC = new javax.swing.JPanel();
        jTextField_modelLOC = new javax.swing.JTextField();
        jButton_modelLOC = new javax.swing.JButton();
        jLabel_datamodel00 = new javax.swing.JLabel();
        jLabel_datamodel01 = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_datasetLOC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lokasi Dataset", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 14))); // NOI18N

        jButton_datasetLOC.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_datasetLOC.setText("Browse");
        jButton_datasetLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_datasetLOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_datasetLOCLayout = new javax.swing.GroupLayout(jPanel_datasetLOC);
        jPanel_datasetLOC.setLayout(jPanel_datasetLOCLayout);
        jPanel_datasetLOCLayout.setHorizontalGroup(
            jPanel_datasetLOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datasetLOCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_datasetLOC)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datasetLOCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_datasetLOC)
                .addGap(113, 113, 113))
        );
        jPanel_datasetLOCLayout.setVerticalGroup(
            jPanel_datasetLOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datasetLOCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_datasetLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_datasetLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel_modelLOC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lokasi Hasil Pemodelan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 14))); // NOI18N

        jButton_modelLOC.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_modelLOC.setText("Browse");
        jButton_modelLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modelLOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_modelLOCLayout = new javax.swing.GroupLayout(jPanel_modelLOC);
        jPanel_modelLOC.setLayout(jPanel_modelLOCLayout);
        jPanel_modelLOCLayout.setHorizontalGroup(
            jPanel_modelLOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modelLOCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_modelLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_modelLOCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_modelLOC)
                .addGap(110, 110, 110))
        );
        jPanel_modelLOCLayout.setVerticalGroup(
            jPanel_modelLOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modelLOCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField_modelLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_modelLOC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_datamodel00.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_datamodel00.setText("Silahkan memilih dataset dan file untuk menyimpan");

        jLabel_datamodel01.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel_datamodel01.setText("hasil pemodelan yang akan digunakan");

        jButton_next.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_datamodel00, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel_modelLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(jPanel_datasetLOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel_datamodel01))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_datamodel00)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_datamodel01)
                .addGap(38, 38, 38)
                .addComponent(jPanel_datasetLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel_modelLOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_next)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aksi yang dilakukan jika user menekan tombol Browse untuk memilih
     * lokasi dataset
     * @param evt 
     */
    private void jButton_datasetLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_datasetLOCActionPerformed
        //KAMUS
        int result;
        File selectedFile;
        
        //ALGORITMA
        JFileChooser fileChooser = new JFileChooser();
        
        // penambahan opsi untuk mem-filter file yang berekstensi .arff 
        fileChooser.addChoosableFileFilter(new ExtensionFilter("arff","File in ARFF format") );
        
        // inisiasi direktori awal pencarian file pada direktori home
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // jika user sudah memilih sebuah file
            selectedFile = fileChooser.getSelectedFile();
            jTextField_datasetLOC.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton_datasetLOCActionPerformed

    /**
     * Aksi yang akan dilakukan jika user menekan tombol Browse untuk
     * menentukan lokasi file penyimpan hasil pemodelan
     * @param evt 
     */
    private void jButton_modelLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modelLOCActionPerformed
        //KAMUS
        int result;
        File selectedFile;
        
        //ALGORITMA
        JFileChooser fileChooser = new JFileChooser();
        
        // penambahan opsi untuk mem-filter file yang berekstensi .arff 
        fileChooser.addChoosableFileFilter(new ExtensionFilter("dat","File in DAT format") );
        
        // inisiasi direktori awal pencarian file pada direktori home
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // jika user sudah memilih sebuah file
            selectedFile = fileChooser.getSelectedFile();
            jTextField_modelLOC.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton_modelLOCActionPerformed

    /**
     * Aksi yang akan dilakukan jika user menekan tombol Next,
     * dimana user akan diarahkan ke halaman pembentukan model (ModelLearnerSPAM100).
     * Selain itu, akan dilakukan validasi input terhadap lokasi dataset dan file model.
     * User akan dapat mengakses ModelLearnerSPAM100 jika kedua lokasi sudah ditentukan.
     * @param evt 
     */
    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        //KAMUS
        String[] args = new String[2];
        
        //ALGORITMA
        
        // validasi input lokasi dataset dan model
        if (jTextField_datasetLOC.getText().equals("") || jTextField_modelLOC.getText().equals("")) {
            if (jTextField_datasetLOC.getText().equals("") && jTextField_modelLOC.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Anda belum memilih lokasi dataset dan hasil pemodelan", "Invalid Next Action", JOptionPane.WARNING_MESSAGE);
            } else if (jTextField_datasetLOC.getText().equals("") && !jTextField_modelLOC.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Anda belum memilih lokasi dataset", "Invalid Next Action", JOptionPane.WARNING_MESSAGE);
            } else if (!jTextField_datasetLOC.getText().equals("") && jTextField_modelLOC.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Anda belum memilih lokasi hasil pemodelan", "Invalid Next Action", JOptionPane.WARNING_MESSAGE);
            } 
        } else {
            // mengirimkan lokasi dataset dan hasil pemodelan kepada bagian Model Learning
            args[0] = jTextField_datasetLOC.getText();
            args[1] = jTextField_modelLOC.getText();
            ModelLearnerSPAM100.main(args);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Model_SPAM100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Model_SPAM100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Model_SPAM100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Model_SPAM100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Model_SPAM100().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_datasetLOC;
    private javax.swing.JButton jButton_modelLOC;
    private javax.swing.JButton jButton_next;
    private javax.swing.JLabel jLabel_datamodel00;
    private javax.swing.JLabel jLabel_datamodel01;
    private javax.swing.JPanel jPanel_datasetLOC;
    private javax.swing.JPanel jPanel_modelLOC;
    private javax.swing.JTextField jTextField_datasetLOC;
    private javax.swing.JTextField jTextField_modelLOC;
    // End of variables declaration//GEN-END:variables
}
